services:
  - type: web
    name: birthday-website
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd server && npm install && node index.js
    envVars:
      - key: NODE_ENV
        value: production
